"""add new module tables"""

revision = 'afa3fc3d28c5'
down_revision = '8442c332232d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('contract_standard', sa.Enum('FIDIC_RED', 'FIDIC_YELLOW', 'FIDIC_SILVER', 'FIDIC_GOLD', 'IR_GCC', 'IR_SCC', 'CUSTOM', name='contract_standard_enum', create_constraint=True), nullable=False),
    sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('revised_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('commencement_date', sa.Date(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('dlp_months', sa.Integer(), nullable=False),
    sa.Column('eot_methodology', sa.Enum('PROSPECTIVE', 'IMPACTED_AS_PLANNED', 'WINDOWS', 'TIA', name='eot_methodology_enum', create_constraint=True), nullable=False),
    sa.Column('ld_formula', sa.JSON(), nullable=True),
    sa.Column('notice_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_type', sa.Enum('OWNER', 'CONTRACTOR', 'SUBCONTRACTOR', 'PMC', 'VENDOR', 'OEM', 'REGULATORY', 'TPI', name='org_type_enum', create_constraint=True), nullable=False),
    sa.Column('org_name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('rbac_tier', sa.Enum('L1', 'L2', 'L3', 'L4', 'L5', 'L6', name='rbac_tier_enum', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module_access', sa.JSON(), nullable=True),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('corridors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('length_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('station_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('rbac_tier', sa.Enum('L1', 'L2', 'L3', 'L4', 'L5', 'L6', name='rbac_tier_enum', create_constraint=True), nullable=False),
    sa.Column('ai_access_level', sa.Enum('FULL', 'PARTIAL', 'LIMITED', 'NONE', 'META_AI', name='ai_access_level_enum', create_constraint=True), nullable=False),
    sa.Column('package_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE', 'APPROVAL', 'REJECTION', 'CONFIG_RELOAD', 'LOGIN', 'LOGOUT', name='audit_action_enum', create_constraint=True), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.Column('actor_person_id', sa.UUID(), nullable=True),
    sa.Column('actor_agent_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('corridor_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'LOCKED', 'SUPERSEDED', name='baseline_status_enum', create_constraint=True), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('import_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dprs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVIEWED', 'APPROVED', 'REJECTED', name='dpr_status_enum', create_constraint=True), nullable=False),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('location_lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('manpower_count', sa.Integer(), nullable=True),
    sa.Column('equipment_count', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('subsystem_type', sa.Enum('CIVIL', 'ELEC', 'SIG', 'TEL', 'TVS', 'BMS', 'SCADA', 'TRACK', 'RS', 'AFC', 'PSD', 'DRAINAGE', 'FIRE_ALARM', 'TRACTION_POWER', 'OHE', 'EARTHWORK', 'BRIDGE', 'TUNNEL', name='subsystem_type_enum', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ACTIVE', 'CLOSED', name='itp_status_enum', create_constraint=True), nullable=False),
    sa.Column('hold_points', sa.JSON(), nullable=True),
    sa.Column('test_standards', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('p6_activity_id', sa.String(length=50), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('baseline_id', sa.UUID(), nullable=True),
    sa.Column('wbs_path', sa.String(length=500), nullable=False),
    sa.Column('subsystem_type', sa.Enum('CIVIL', 'ELEC', 'SIG', 'TEL', 'TVS', 'BMS', 'SCADA', 'TRACK', 'RS', 'AFC', 'PSD', 'DRAINAGE', 'FIRE_ALARM', 'TRACTION_POWER', 'OHE', 'EARTHWORK', 'BRIDGE', 'TUNNEL', name='subsystem_type_enum', create_constraint=True), nullable=False),
    sa.Column('activity_name', sa.String(length=500), nullable=False),
    sa.Column('activity_type', sa.Enum('TASK', 'MILESTONE', 'SUMMARY', 'LOE', 'WBS_SUMMARY', name='activity_type_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'SUSPENDED', name='activity_status_enum', create_constraint=True), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=False),
    sa.Column('planned_finish', sa.Date(), nullable=False),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('original_duration', sa.Integer(), nullable=False),
    sa.Column('remaining_duration', sa.Integer(), nullable=True),
    sa.Column('percent_complete', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('float_days', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('is_near_critical', sa.Boolean(), nullable=False),
    sa.Column('requires_rfi', sa.Boolean(), nullable=False),
    sa.Column('requires_material', sa.Boolean(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('predecessor_id', sa.UUID(), nullable=False),
    sa.Column('successor_id', sa.UUID(), nullable=False),
    sa.Column('dep_type', sa.Enum('FS', 'SS', 'FF', 'SF', name='dependency_type_enum', create_constraint=True), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=True),
    sa.Column('is_cross_package', sa.Boolean(), nullable=False),
    sa.Column('is_cross_subsystem', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['successor_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dpr_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dpr_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('subsystem_type', sa.Enum('CIVIL', 'ELEC', 'SIG', 'TEL', 'TVS', 'BMS', 'SCADA', 'TRACK', 'RS', 'AFC', 'PSD', 'DRAINAGE', 'FIRE_ALARM', 'TRACTION_POWER', 'OHE', 'EARTHWORK', 'BRIDGE', 'TUNNEL', name='subsystem_type_enum', create_constraint=True), nullable=False),
    sa.Column('reported_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity_unit', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['dpr_id'], ['dprs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('rfi_verified_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dpr_reported_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('schedule_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discrepancy_flag', sa.Boolean(), nullable=False),
    sa.Column('discrepancy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('itp_id', sa.UUID(), nullable=True),
    sa.Column('subsystem_type', sa.Enum('CIVIL', 'ELEC', 'SIG', 'TEL', 'TVS', 'BMS', 'SCADA', 'TRACK', 'RS', 'AFC', 'PSD', 'DRAINAGE', 'FIRE_ALARM', 'TRACTION_POWER', 'OHE', 'EARTHWORK', 'BRIDGE', 'TUNNEL', name='subsystem_type_enum', create_constraint=True), nullable=False),
    sa.Column('rfi_number', sa.String(length=50), nullable=False),
    sa.Column('initiator_person_id', sa.UUID(), nullable=False),
    sa.Column('initiator_role', sa.Enum('SITE_ENG', 'PLANNING_ENG', 'CONTRACTOR_SE', name='initiator_role_enum', create_constraint=True), nullable=False),
    sa.Column('routing_target_type', sa.Enum('OWNER_INTERNAL', 'PMC', 'CLIENT', name='routing_target_type_enum', create_constraint=True), nullable=False),
    sa.Column('assigned_inspector_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ASSIGNED', 'INSPECTED', 'APPROVED', 'COMMENTED', 'REJECTED', 'CLOSED', name='rfi_status_enum', create_constraint=True), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('result', sa.Enum('APPROVED', 'APPROVED_WITH_COMMENTS', 'REJECTED', name='rfi_result_enum', create_constraint=True), nullable=True),
    sa.Column('verified_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity_unit', sa.String(length=30), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('location_lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cp_impact_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['assigned_inspector_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['initiator_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['itp_id'], ['itps.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('procurement_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'OPEN'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_orders_pkey'))
    )
    op.drop_table('rfis')
    op.drop_table('progress_measurements')
    op.drop_table('dpr_entries')
    op.drop_table('dependencies')
    op.drop_table('activities')
    op.drop_table('itps')
    op.drop_table('dprs')
    op.drop_table('baselines')
    op.drop_table('packages')
    op.drop_table('audit_events')
    op.drop_table('persons')
    op.drop_table('corridors')
    op.drop_table('roles')
    op.drop_table('programs')
    op.drop_table('organizations')
    op.drop_table('contracts')
    # ### end Alembic commands ###
