"""add procurement models"""

revision = 'fc0a8671c15e'
down_revision = 'afa3fc3d28c5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('STRUCTURAL', 'ELECTRICAL', 'MECHANICAL', 'SIGNALING', 'TELECOM', 'TRACK', 'ROLLING_STOCK', 'CIVIL', 'OTHER', name='material_category_enum', create_constraint=True), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('procurement_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=15), nullable=True),
    sa.Column('vendor_status', sa.Enum('ACTIVE', 'INACTIVE', 'BLACKLISTED', 'UNDER_REVIEW', name='vendor_status_enum', create_constraint=True), nullable=False),
    sa.Column('vendor_tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='vendor_tier_enum', create_constraint=True), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('vendor_score_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('scoring_period', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('delivery_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('compliance_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('price_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('scored_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scored_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'DISPATCHED', 'ACKNOWLEDGED', 'PARTIALLY_DELIVERED', 'DELIVERED', 'UNDER_INSPECTION', 'CLOSED', 'CANCELLED', name='po_status_enum', create_constraint=True), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', 'GBP', 'JPY', name='currency_code_enum', create_constraint=True), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('delivery_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_TRANSIT', 'DELIVERED', 'PARTIALLY_DELIVERED', 'REJECTED', name='delivery_status_enum', create_constraint=True), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=True),
    sa.Column('expected_arrival', sa.Date(), nullable=True),
    sa.Column('actual_arrival', sa.Date(), nullable=True),
    sa.Column('transporter_name', sa.String(length=300), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_number')
    )
    op.create_table('fat_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('test_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'NOTICE_SENT', 'IN_PROGRESS', 'PASSED', 'FAILED', 'CONDITIONALLY_PASSED', 'RETEST_SCHEDULED', name='fat_status_enum', create_constraint=True), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('notice_sent_date', sa.Date(), nullable=True),
    sa.Column('inspector_name', sa.String(length=200), nullable=True),
    sa.Column('inspector_id', sa.UUID(), nullable=True),
    sa.Column('test_location', sa.String(length=500), nullable=True),
    sa.Column('test_report_url', sa.String(length=1000), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('retest_of', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['retest_of'], ['fat_tests.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_number')
    )
    op.create_table('po_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('delivered_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('po_line_item_id', sa.UUID(), nullable=False),
    sa.Column('delivered_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('accepted_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['po_line_item_id'], ['po_line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_items')
    op.drop_table('po_line_items')
    op.drop_table('fat_tests')
    op.drop_table('deliveries')
    op.drop_table('purchase_orders')
    op.drop_table('vendor_score_history')
    op.drop_table('vendors')
    op.drop_table('procurement_orders')
    op.drop_table('materials')
    # ### end Alembic commands ###
